# Default Configuration for AudioVisualizer

audio:
  input_type: "file" # options: "microphone", "file"
  file_path: "/Users/carter/Music/Music/Media.localized/Music/Unknown Artist/Unknown Album/Traffic - Dear Mr. Fantasy 1967 Remastered.mp3"
  sample_rate: 44100
  chunk_size: 512
  channels: 1

visualizer:
  type: "browser" # options: "terminal", "browser"
  fps: 30
  fft_size: 1024
  frequency_range: [20, 20000]

terminal:
  display_type: "line" # options: "bar", "line", "braille"
  color_profile: "default"

browser:
  port: 8000
  host: "0.0.0.0"

processing:
  volume: 1.0
  pitch: 0.4
  timescale: 1.0
  modulation_freq: 0.0
  modulation_type: "ring" # "ring" or "am"
  lpf_cutoff: 20000.0
  hpf_cutoff: 0.0
